# .github/dependabot.yml
version: 2

updates:
  # npm dependencies (package.json)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/New_York"  # Change to your timezone
    open-pull-requests-limit: 10
    reviewers:
      - "SamuelIVX"  # Auto-assign PRs to yourself
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    # Group minor and patch updates to reduce PR spam
    groups:
      development-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "typescript"
          - "@typescript-eslint/*"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "react*"
          - "next"
        update-types:
          - "patch"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    reviewers:
      - "SamuelIVX"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"